# Generated by Django 3.2.9 on 2021-12-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='replied',
            field=models.BooleanField(default=False),
        ),
    ]
